# Generated by Django 3.2.25 on 2026-02-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='no',
            field=models.IntegerField(null=True),
        ),
    ]
