# Generated by Django 3.2.25 on 2026-02-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_list_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='no',
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
